site_name: "Abigale 's Blog"
remote_branch: main
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# 启用站点导航
nav:
  - Home: index.md
  - Numerical Optimization:
      - Overview: numerical_optimization/overview.md
      - Equations: numerical_optimization/LinearEquation.md
      - Newton's Method: numerical_optimization/newton_method.md

# Markdown 扩展
markdown_extensions:
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# Google Analytics
google_analytics:
  - "UA-156919721-1"
  - "auto"

edit_uri:

plugins:
  - search