site_name: "Your Site Name"
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# 启用站点导航
nav:
  - Home: index.md
  - Numerical Optimization:
      - Overview: numerical_optimization/overview.md
      - Gradient Descent: numerical_optimization/gradient_descent.md
      - Newton's Method: numerical_optimization/newton_method.md
  # - Machine Learning:
  #     - Supervised Learning: ml/supervised_learning.md
  #     - Unsupervised Learning: ml/unsupervised_learning.md
  #     - Reinforcement Learning: ml/reinforcement_learning.md

# Markdown 扩展
markdown_extensions:
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js